backend:
  name: git-gateway
  repo: RedCiudadana/Conecta-Futuro
  branch: main
  identity_url: https://auth.decapbridge.com/sites/e0f05e32-27b9-4041-9b01-a06878fc1d6b
  gateway_url: https://gateway.decapbridge.com
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "cursos"
    label: "Cursos"
    folder: "src/content/cursos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título del Curso", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - label: "Sesiones"
        name: "sesiones"
        widget: "list"
        label_singular: "Sesión"
        fields:
          - { label: "Nombre de la sesión", name: "nombre", widget: "string" }
          - label: "Bienvenida / Video de Introducción"
            name: "bienvenida"
            widget: "object"
            fields:
              - { label: "Tipo", name: "tipo", widget: "hidden", default: "video" }
              - { label: "URL del video", name: "contenido", widget: "string" }

          - label: "Teoría / Texto"
            name: "teoria"
            widget: "object"
            fields:
              - { label: "Tipo", name: "tipo", widget: "hidden", default: "texto" }
              - { label: "Contenido", name: "contenido", widget: "markdown" }

          - label: "Video Zoom Sesión / Video de youtube"
            name: "video_zoom"
            widget: "object"
            fields:
              - { label: "Tipo", name: "tipo", widget: "hidden", default: "youtube" }
              - { label: "URL del video", name: "contenido", widget: "string" }

          - label: "Handout / PDF"
            name: "handout"
            widget: "object"
            fields:
              - { label: "Tipo", name: "tipo", widget: "hidden", default: "pdf" }
              - { label: "Archivo PDF", name: "contenido", widget: "file", media_library: { allow_multiple: false }, required: false }
