backend:
  name: git-gateway
  repo: RedCiudadana/Conecta-Futuro
  branch: main
  identity_url: https://auth.decapbridge.com/sites/e0f05e32-27b9-4041-9b01-a06878fc1d6b
  gateway_url: https://gateway.decapbridge.com
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "instructores"
    label: "Instructores"
    folder: "src/content/instructores"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Especialización", name: "especializacion", widget: "string" }
      - { label: "Descripción General", name: "descripcion", widget: "text" }
      - { label: "Foto", name: "foto", widget: "image", required: false }
  - name: "cursos"
    label: "Cursos"
    folder: "src/content/cursos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título del Curso", name: "titulo", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Nivel", name: "nivel", widget: "select", options: ["Básico", "Intermedio", "Avanzado"] }
      - { label: "Duración", name: "duracion", widget: "string" }
      - { label: "Enlace de Contenido", name: "enlace_contenido", widget: "string" }
      - { label: "Enlace de Registro", name: "enlace_registro", widget: "string" }
      - label: "Instructor"
        name: "instructor"
        widget: "relation"
        collection: "instructores"
        search_fields: ["nombre"]
        value_field: "nombre"
        display_fields: ["nombre"]
  - name: "sesiones"
    label: "Sesiones"
    folder: "src/content/sesiones"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Curso"
        name: "curso"
        widget: "relation"
        collection: "cursos"
        search_fields: ["titulo"]
        value_field: "titulo"
        display_fields: ["titulo"]
      - { label: "Nombre de la Sesión", name: "nombre_sesion", widget: "string" }
      - { label: "Bienvenida / Video de Introducción", name: "bienvenida", widget: "string" }
      - { label: "Teoría / Texto", name: "teoria", widget: "markdown" }
      - { label: "Video Zoom Sesión / Video de YouTube", name: "video_zoom", widget: "string" }
      - { label: "Handout / PDF", name: "handout", widget: "file", media_library: { allow_multiple: false }, required: false }
